### ISSUE TITLE
Commit count is incorrect

### ISSUE THREAD

**Issue by protoEvangelion** [drewbrokke/jack-cli#18]
After running `jack` it starts to count the commits in the upper right corner.  Once the count stops it is incorrect:

![image](https://user-images.githubusercontent.com/20076677/29179967-11845788-7dab-11e7-829d-200076274709.png)

While `git rev-list --count master` yields: **224325** commits

**Comment by drewbrokke** [comment]
This one is tricky because what I'm really counting is the number of lines that match the Git SHA regex.  Some commit messages have SHAs in them (like revert commits), so it inflates the count.

The purpose of the count is to give you an idea of your relative position in a potentially gigantic list, so I'm hesitant to spend any significant time to get it exactly accurate.  I originally had it say "Line" instead of "Commit", so I may revert back to that.

**Comment by protoEvangelion** [comment]
Ahh I see.  Thanks for the clarification :)
