### ISSUE TITLE
Navigating through commit SHAs occasionally highlights the author

### ISSUE THREAD

**Issue by jwu910** [drewbrokke/jack-cli#24]
Receiving an error as sometimes navigating down highlights the commit author rather than the SHA, and attempts to use their (in this case Liferay) email name as the commit SHA.

**Comment by drewbrokke** [comment]
This is a fun regex puzzle, though if there's a way to identify commits *without* using regex I'll take it in a heartbeat ;)

**Comment by jwu910** [comment]
Maybe a regex that catches lines starting with "commit" followed by SHA regex?

**Comment by drewbrokke** [comment]
I don't think that would work simply because we can't depend on commits being displayed in any particular way.  If you pass in the `--oneline` flag, for example, you'll get the commit hash at the beginning of the line.  And if you use the `--pretty` flag, you can format it in any way you choose.

I think the solution would to be more exclusive with the boundaries surrounding the commit.  Most likely the commit will either start the line or have some sort of other character bordering it, so we can account for that.

This is the line that needs to change: https://github.com/drewbrokke/jack-cli/blob/master/src/redux/reducers.ts#L3

**Comment by drewbrokke** [comment]
> I think the solution would to be more exclusive with the boundaries surrounding the commit. Most likely the commit will either start the line or have some sort of other character bordering it, so we can account for that.

Hmm, on second thought this may not work either.  If we did this it may end up breaking someone's formatting.  It seems right now to err on the side of being too inclusive.  Perhaps the real solution is to make the error less obnoxious ;)

**Comment by drewbrokke** [comment]
This issue should be solved by the new feature added for https://github.com/drewbrokke/jack-cli/issues/25.  The blacklist patterns configuration option will be available in the next release.
